# Generated by Django 2.2 on 2020-03-10 19:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('crispysample', '0004_invite_inviteguest'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
